/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    tutorialSidebar: [
	'introduction',
	'development',
	{
	    type: 'category',
	    label: 'DTCC Model',
	    link: {
		type: 'generated-index',
	    },
	    collapsed: false,
	    items: [
		'dtcc-model/introduction',
		'dtcc-model/installation',
		'dtcc-model/usage',
		'dtcc-model/development',
	    ],
	},
	{
	    type: 'category',
	    label: 'DTCC Core',
	    link: {
		type: 'generated-index',
	    },
	    collapsed: false,
	    items: [
		'dtcc-core/introduction',
		'dtcc-core/installation',
		'dtcc-core/usage',
		'dtcc-core/development',
	    ],
	},
	{
	    type: 'category',
	    label: 'DTCC Builder',
	    link: {
		type: 'generated-index',
	    },
	    collapsed: false,
	    items: [
		'dtcc-builder/introduction',
		'dtcc-builder/installation',
		'dtcc-builder/usage',
		'dtcc-builder/development',
	    ],
	},
	{
	    type: 'category',
	    label: 'DTCC Viewer',
	    link: {
		type: 'generated-index',
	    },
	    collapsed: false,
	    items: [
		'dtcc-viewer/introduction',
		'dtcc-viewer/installation',
		'dtcc-viewer/usage',
		'dtcc-viewer/development',
	    ],
	},
	{
	    type: 'category',
	    label: 'DTCC Docker',
	    link: {
		type: 'generated-index',
	    },
	    collapsed: false,
	    items: [
		'dtcc-docker/introduction',
		'dtcc-docker/installation',
		'dtcc-docker/usage',
		'dtcc-docker/development',
	    ],
	},
	{
	    type: 'category',
	    label: 'DTCC Doc',
	    link: {
		type: 'generated-index',
	    },
	    collapsed: false,
	    items: [
		'dtcc-doc/introduction',
		'dtcc-doc/installation',
		'dtcc-doc/usage',
		'dtcc-doc/development',
	    ],
	},
    ]

};

module.exports = sidebars;
