name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          pwd && ls -alt
          sh ./bin/dtcc-build-documentation && cd website && npm install && npm run build
          pwd
          ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: website/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: website-build
          path: website/build/

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-north-1

      - name: Deploy to S3
        run: |
          cd website/build
          aws s3 ls s3://$S3_BUCKET
          aws s3 sync . s3://$S3_BUCKET
